[sources.foo]
    type = "stdin"

[transforms.grok]
    type = "grok_parser"
    inputs = ["foo"]
    pattern = "%{TIMESTAMP_ISO8601:timestamp} %{GREEDYDATA:message}"

    drop_field = true
    field = "message"

[sinks.bar]
    inputs = ["grok"]
    type = "console"
    encoding = "text"
